#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : npb
Version  : 3.4.3
Release  : 5
URL      : https://www.nas.nasa.gov/assets/npb/NPB3.4.3.tar.gz
Source0  : https://www.nas.nasa.gov/assets/npb/NPB3.4.3.tar.gz
Source1  : npb-run-omp.sh
Source2  : npb-run-mpi.sh
Summary  : NAS Parallel Benchmarks
Group    : Development/Tools
License  : NASA-1.3
Requires: npb-bin = %{version}-%{release}
Requires: npb-openmpi = %{version}-%{release}
Requires: openmpi
BuildRequires : openmpi-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: suite_def.patch
Patch2: mpi_def.patch
Patch3: omp_def.patch
Patch4: makefile.patch
Patch5: make_common.patch

%description
NAS Parallel Benchmarks Version 3.4.3 (NPB3.4.3)
--------------------------------------------------

%package bin
Summary: bin components for the npb package.
Group: Binaries

%description bin
bin components for the npb package.


%package openmpi
Summary: openmpi components for the npb package.
Group: Default

%description openmpi
openmpi components for the npb package.


%prep
%setup -q -n NPB3.4.3
cd %{_builddir}/NPB3.4.3
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
pushd ..
cp -a NPB3.4.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720067336
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720067336
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
mkdir -p %{buildroot}/usr
install -m 0755 %{_sourcedir}/npb-run-omp.sh %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr
install -m 0755 %{_sourcedir}/npb-run-mpi.sh %{buildroot}/usr/bin
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/bt.A.x
/V3/usr/bin/bt.B.x
/V3/usr/bin/bt.C.x
/V3/usr/bin/bt.D.x
/V3/usr/bin/bt.E.x
/V3/usr/bin/bt.S.x
/V3/usr/bin/bt.W.x
/V3/usr/bin/cg.A.x
/V3/usr/bin/cg.B.x
/V3/usr/bin/cg.C.x
/V3/usr/bin/cg.D.x
/V3/usr/bin/cg.E.x
/V3/usr/bin/cg.S.x
/V3/usr/bin/cg.W.x
/V3/usr/bin/ep.A.x
/V3/usr/bin/ep.B.x
/V3/usr/bin/ep.C.x
/V3/usr/bin/ep.D.x
/V3/usr/bin/ep.E.x
/V3/usr/bin/ep.S.x
/V3/usr/bin/ep.W.x
/V3/usr/bin/ft.A.x
/V3/usr/bin/ft.B.x
/V3/usr/bin/ft.C.x
/V3/usr/bin/ft.D.x
/V3/usr/bin/ft.E.x
/V3/usr/bin/ft.S.x
/V3/usr/bin/ft.W.x
/V3/usr/bin/is.A.x
/V3/usr/bin/is.B.x
/V3/usr/bin/is.C.x
/V3/usr/bin/is.S.x
/V3/usr/bin/is.W.x
/V3/usr/bin/lu.A.x
/V3/usr/bin/lu.B.x
/V3/usr/bin/lu.C.x
/V3/usr/bin/lu.D.x
/V3/usr/bin/lu.E.x
/V3/usr/bin/lu.S.x
/V3/usr/bin/lu.W.x
/V3/usr/bin/mg.A.x
/V3/usr/bin/mg.B.x
/V3/usr/bin/mg.C.x
/V3/usr/bin/mg.D.x
/V3/usr/bin/mg.E.x
/V3/usr/bin/mg.S.x
/V3/usr/bin/mg.W.x
/V3/usr/bin/sp.A.x
/V3/usr/bin/sp.B.x
/V3/usr/bin/sp.C.x
/V3/usr/bin/sp.D.x
/V3/usr/bin/sp.E.x
/V3/usr/bin/sp.S.x
/V3/usr/bin/sp.W.x
/V3/usr/bin/ua.A.x
/V3/usr/bin/ua.B.x
/V3/usr/bin/ua.C.x
/V3/usr/bin/ua.D.x
/V3/usr/bin/ua.S.x
/V3/usr/bin/ua.W.x
/usr/bin/bt.A.x
/usr/bin/bt.B.x
/usr/bin/bt.C.x
/usr/bin/bt.D.x
/usr/bin/bt.E.x
/usr/bin/bt.S.x
/usr/bin/bt.W.x
/usr/bin/cg.A.x
/usr/bin/cg.B.x
/usr/bin/cg.C.x
/usr/bin/cg.D.x
/usr/bin/cg.E.x
/usr/bin/cg.S.x
/usr/bin/cg.W.x
/usr/bin/ep.A.x
/usr/bin/ep.B.x
/usr/bin/ep.C.x
/usr/bin/ep.D.x
/usr/bin/ep.E.x
/usr/bin/ep.S.x
/usr/bin/ep.W.x
/usr/bin/ft.A.x
/usr/bin/ft.B.x
/usr/bin/ft.C.x
/usr/bin/ft.D.x
/usr/bin/ft.E.x
/usr/bin/ft.S.x
/usr/bin/ft.W.x
/usr/bin/is.A.x
/usr/bin/is.B.x
/usr/bin/is.C.x
/usr/bin/is.S.x
/usr/bin/is.W.x
/usr/bin/lu.A.x
/usr/bin/lu.B.x
/usr/bin/lu.C.x
/usr/bin/lu.D.x
/usr/bin/lu.E.x
/usr/bin/lu.S.x
/usr/bin/lu.W.x
/usr/bin/mg.A.x
/usr/bin/mg.B.x
/usr/bin/mg.C.x
/usr/bin/mg.D.x
/usr/bin/mg.E.x
/usr/bin/mg.S.x
/usr/bin/mg.W.x
/usr/bin/npb-run-mpi.sh
/usr/bin/npb-run-omp.sh
/usr/bin/sp.A.x
/usr/bin/sp.B.x
/usr/bin/sp.C.x
/usr/bin/sp.D.x
/usr/bin/sp.E.x
/usr/bin/sp.S.x
/usr/bin/sp.W.x
/usr/bin/ua.A.x
/usr/bin/ua.B.x
/usr/bin/ua.C.x
/usr/bin/ua.D.x
/usr/bin/ua.S.x
/usr/bin/ua.W.x

%files openmpi
%defattr(-,root,root,-)
/V3/usr/lib64/openmpi/bin/bt.A.x
/V3/usr/lib64/openmpi/bin/bt.B.x
/V3/usr/lib64/openmpi/bin/bt.C.x
/V3/usr/lib64/openmpi/bin/bt.D.x
/V3/usr/lib64/openmpi/bin/bt.E.x
/V3/usr/lib64/openmpi/bin/bt.F.x
/V3/usr/lib64/openmpi/bin/bt.S.x
/V3/usr/lib64/openmpi/bin/bt.W.x
/V3/usr/lib64/openmpi/bin/cg.A.x
/V3/usr/lib64/openmpi/bin/cg.B.x
/V3/usr/lib64/openmpi/bin/cg.C.x
/V3/usr/lib64/openmpi/bin/cg.D.x
/V3/usr/lib64/openmpi/bin/cg.E.x
/V3/usr/lib64/openmpi/bin/cg.F.x
/V3/usr/lib64/openmpi/bin/cg.S.x
/V3/usr/lib64/openmpi/bin/cg.W.x
/V3/usr/lib64/openmpi/bin/dt.A.x
/V3/usr/lib64/openmpi/bin/dt.B.x
/V3/usr/lib64/openmpi/bin/dt.S.x
/V3/usr/lib64/openmpi/bin/dt.W.x
/V3/usr/lib64/openmpi/bin/ep.A.x
/V3/usr/lib64/openmpi/bin/ep.B.x
/V3/usr/lib64/openmpi/bin/ep.C.x
/V3/usr/lib64/openmpi/bin/ep.D.x
/V3/usr/lib64/openmpi/bin/ep.E.x
/V3/usr/lib64/openmpi/bin/ep.F.x
/V3/usr/lib64/openmpi/bin/ep.S.x
/V3/usr/lib64/openmpi/bin/ep.W.x
/V3/usr/lib64/openmpi/bin/ft.A.x
/V3/usr/lib64/openmpi/bin/ft.B.x
/V3/usr/lib64/openmpi/bin/ft.C.x
/V3/usr/lib64/openmpi/bin/ft.D.x
/V3/usr/lib64/openmpi/bin/ft.E.x
/V3/usr/lib64/openmpi/bin/ft.F.x
/V3/usr/lib64/openmpi/bin/ft.S.x
/V3/usr/lib64/openmpi/bin/ft.W.x
/V3/usr/lib64/openmpi/bin/is.A.x
/V3/usr/lib64/openmpi/bin/is.B.x
/V3/usr/lib64/openmpi/bin/is.C.x
/V3/usr/lib64/openmpi/bin/is.D.x
/V3/usr/lib64/openmpi/bin/is.E.x
/V3/usr/lib64/openmpi/bin/is.S.x
/V3/usr/lib64/openmpi/bin/is.W.x
/V3/usr/lib64/openmpi/bin/lu.A.x
/V3/usr/lib64/openmpi/bin/lu.B.x
/V3/usr/lib64/openmpi/bin/lu.C.x
/V3/usr/lib64/openmpi/bin/lu.D.x
/V3/usr/lib64/openmpi/bin/lu.E.x
/V3/usr/lib64/openmpi/bin/lu.F.x
/V3/usr/lib64/openmpi/bin/lu.S.x
/V3/usr/lib64/openmpi/bin/lu.W.x
/V3/usr/lib64/openmpi/bin/mg.A.x
/V3/usr/lib64/openmpi/bin/mg.B.x
/V3/usr/lib64/openmpi/bin/mg.C.x
/V3/usr/lib64/openmpi/bin/mg.D.x
/V3/usr/lib64/openmpi/bin/mg.E.x
/V3/usr/lib64/openmpi/bin/mg.F.x
/V3/usr/lib64/openmpi/bin/mg.S.x
/V3/usr/lib64/openmpi/bin/mg.W.x
/V3/usr/lib64/openmpi/bin/sp.A.x
/V3/usr/lib64/openmpi/bin/sp.B.x
/V3/usr/lib64/openmpi/bin/sp.C.x
/V3/usr/lib64/openmpi/bin/sp.D.x
/V3/usr/lib64/openmpi/bin/sp.E.x
/V3/usr/lib64/openmpi/bin/sp.F.x
/V3/usr/lib64/openmpi/bin/sp.S.x
/V3/usr/lib64/openmpi/bin/sp.W.x
/usr/lib64/openmpi/bin/bt.A.x
/usr/lib64/openmpi/bin/bt.B.x
/usr/lib64/openmpi/bin/bt.C.x
/usr/lib64/openmpi/bin/bt.D.x
/usr/lib64/openmpi/bin/bt.E.x
/usr/lib64/openmpi/bin/bt.F.x
/usr/lib64/openmpi/bin/bt.S.x
/usr/lib64/openmpi/bin/bt.W.x
/usr/lib64/openmpi/bin/cg.A.x
/usr/lib64/openmpi/bin/cg.B.x
/usr/lib64/openmpi/bin/cg.C.x
/usr/lib64/openmpi/bin/cg.D.x
/usr/lib64/openmpi/bin/cg.E.x
/usr/lib64/openmpi/bin/cg.F.x
/usr/lib64/openmpi/bin/cg.S.x
/usr/lib64/openmpi/bin/cg.W.x
/usr/lib64/openmpi/bin/dt.A.x
/usr/lib64/openmpi/bin/dt.B.x
/usr/lib64/openmpi/bin/dt.S.x
/usr/lib64/openmpi/bin/dt.W.x
/usr/lib64/openmpi/bin/ep.A.x
/usr/lib64/openmpi/bin/ep.B.x
/usr/lib64/openmpi/bin/ep.C.x
/usr/lib64/openmpi/bin/ep.D.x
/usr/lib64/openmpi/bin/ep.E.x
/usr/lib64/openmpi/bin/ep.F.x
/usr/lib64/openmpi/bin/ep.S.x
/usr/lib64/openmpi/bin/ep.W.x
/usr/lib64/openmpi/bin/ft.A.x
/usr/lib64/openmpi/bin/ft.B.x
/usr/lib64/openmpi/bin/ft.C.x
/usr/lib64/openmpi/bin/ft.D.x
/usr/lib64/openmpi/bin/ft.E.x
/usr/lib64/openmpi/bin/ft.F.x
/usr/lib64/openmpi/bin/ft.S.x
/usr/lib64/openmpi/bin/ft.W.x
/usr/lib64/openmpi/bin/is.A.x
/usr/lib64/openmpi/bin/is.B.x
/usr/lib64/openmpi/bin/is.C.x
/usr/lib64/openmpi/bin/is.D.x
/usr/lib64/openmpi/bin/is.E.x
/usr/lib64/openmpi/bin/is.S.x
/usr/lib64/openmpi/bin/is.W.x
/usr/lib64/openmpi/bin/lu.A.x
/usr/lib64/openmpi/bin/lu.B.x
/usr/lib64/openmpi/bin/lu.C.x
/usr/lib64/openmpi/bin/lu.D.x
/usr/lib64/openmpi/bin/lu.E.x
/usr/lib64/openmpi/bin/lu.F.x
/usr/lib64/openmpi/bin/lu.S.x
/usr/lib64/openmpi/bin/lu.W.x
/usr/lib64/openmpi/bin/mg.A.x
/usr/lib64/openmpi/bin/mg.B.x
/usr/lib64/openmpi/bin/mg.C.x
/usr/lib64/openmpi/bin/mg.D.x
/usr/lib64/openmpi/bin/mg.E.x
/usr/lib64/openmpi/bin/mg.F.x
/usr/lib64/openmpi/bin/mg.S.x
/usr/lib64/openmpi/bin/mg.W.x
/usr/lib64/openmpi/bin/sp.A.x
/usr/lib64/openmpi/bin/sp.B.x
/usr/lib64/openmpi/bin/sp.C.x
/usr/lib64/openmpi/bin/sp.D.x
/usr/lib64/openmpi/bin/sp.E.x
/usr/lib64/openmpi/bin/sp.F.x
/usr/lib64/openmpi/bin/sp.S.x
/usr/lib64/openmpi/bin/sp.W.x
